# Use the official Nginx image as base
FROM nginx:latest

# Copy the contents of the local 'public' directory to the Nginx web root
COPY . /usr/share/nginx/html

# Expose the port the app runs on (default for Nginx is 80)
EXPOSE 80
